### ISSUE TITLE
SDK的头文件引用有bug

### ISSUE THREAD

**Issue by Somiona** [MikuPy2001/CQSDK#1]
我的IDE是vs2019 preview，CQ_APP下的appmain.cpp 里的 #include 无法正确的找到头文件。在我这里给它改成 #include "../CQ_SDK/CQSDK.h" 之后可以正常工作啦
![image](https://user-images.githubusercontent.com/20739885/53769150-0bcead00-3ea9-11e9-99c1-9604bc47adc0.png)

修改后：
```
#pragma comment(lib,"CQ_SDK.lib")
#include "../CQ_SDK/CQSDK.h" //TODO: 这里

//----我为什么要修改这个ID----
//这是您的插件名称,一个独一无二的名称

//----我应该如何修改这个ID----
//首先您应该修改下方的CQAPPID
//然后修改项目名称      (它会指引VS使用这个名称生成文件)
//最后修改json文件名称
```

**Comment by MikuPy2001** [comment]
默认情况下, 工程已经将CQ_SDK目录添加到Include搜索路径,
所以使用的是#include <...>查找而非#include "..."
您是否是自己建立的工程
建议将CQ_SDK目录添加到您的工程Include搜索路径

**Comment by Somiona** [comment]
我确认下是不是vs2019的锅
