### ISSUE TITLE
API.cpp中CQ::getGroupMemberList的另外一些BUG

### ISSUE THREAD

**Issue by zhongjianhua163** [MikuPy2001/CQSDK#12]
我这些天发现CQ::getGroupMemberList()这个频繁崩溃。(DEMO代码一天崩溃十次以上)
反复远程调试后发现是data偶尔接收了一个非法指针导致的，下面先看看原本的代码：
```
//取群成员列表
std::vector<GroupMemberInfo> CQ::getGroupMemberList(长整数型 群号) {
	文本型 data = CQ_getGroupMemberList(getAuthCode(), 群号);
	vector<GroupMemberInfo> infovector;
	if (data==nullptr)  return infovector;
	if (data[0] == '\0')return infovector;

	Unpack u(base64_decode(data));
	auto i = u.getInt();
	while (i-- && u.len() > 0)
	{
		//infovector.push_back(GroupMemberInfo(u.getchars()));
		infovector.emplace_back(u.getUnpack());
	}
	return infovector;
}
```
崩溃时 data==0xFFFFD8EA，那么data[0]就内存读取非法了。
这个应该是酷Q本身的问题(需要跟作者反馈修复)，但是SDK里可以(也应该)避免崩溃。比如把 data==nullptr 改成 (int)data <=0，或者使用API:isBadReadPtr()来判断一下。

另外，这里也发现了一个明显的内存泄露。经过我长时间的调试和观察确认了，data指向的内存并没有在使用完毕后释放或者复用。
我不太清楚酷Q使用的是HeapAlloc(易语言自身使用的内存分配方式)  还是malloc(酷Q作者自己申请的内存)。 但是我使用了 Free((void*)data) 来释放内存，没有发现问题，内存能正常释放(跟踪内存地址确认了内存的成功释放)，也未出现崩溃。

最后，我猜测，以下接口的使用时应该也需要释放内存：
文本型 CQ_getCookies()
文本型 CQ_getRecord()
文本型 CQ_getAppDirectory()
文本型 CQ_getLoginNick()
文本型 CQ_getGroupMemberInfoV2()
文本型 CQ_getStrangerInfo()
文本型 CQ_getGroupMemberList()
文本型 CQ_getGroupList()

**Comment by MikuPy2001** [comment]
isBadReadPtr需要测试数据的长度,API不返回文本长度,所以无法使用,现在仅仅用data <=0判断了一下,不知道你有没有什么更好的建议

**Comment by MikuPy2001** [comment]
已经修复,如果还有问题可以重启本iss

**Comment by zhongjianhua163** [comment]
还有一处地方崩溃，我正在找原因。希望这两天能把它定位到！

**Comment by Coxxs** [comment]
@MikuPy2001 
1. 【重要】酷Q会在合适的时机自动释放内存，应用试图释放内存会造成酷Q释放内存时发生致命错误，建议尽快撤销 https://github.com/MikuPy2001/CQSDK/commit/96d4bd2c5b4a329517142f38e0f15af59bf1c7c1。
2. 函数返回负值代表获取失败（可能是调用过于频繁），在正常情况下不应该出现，我们之后会修正该问题（返回0）。**已修复**
