### ISSUE TITLE
关于#iss12里的对内存泄露的错误判断，可能需要回退代码！！

### ISSUE THREAD

**Issue by zhongjianhua163** [MikuPy2001/CQSDK#13]
#iss12中所说的内存泄露BUG并不存在！！！
我当时测试了两三个小时，自以为觉得时间够长了，也没出现复用，就认定为是BUG。

然而之后的更长的时间后出现崩溃，异常的信息是还是内存读取非法，但是这次指针看着并不像非法指针，与正常指针没有差异，但是内存已经不存在。所以我就怀疑是我之前加了释放内存代码导致的。进一步测试发现，果然是这个原因。酷Q内部会复用内存地址，所以并不存在内存泄露一说。

所以请回退代码吧，只需要判断指针是否为负数就行了，不需要释放，，也不能释放！
抱歉，下次我会做更仔细的测试再提交ISS。

![QQ图片20190616221633](https://user-images.githubusercontent.com/51079858/59565317-7e445100-9084-11e9-87e1-cb31d2fca546.png)
![QQ截图20190616221605](https://user-images.githubusercontent.com/51079858/59565318-80a6ab00-9084-11e9-95a8-dbe0c493a5a2.png)
![QQ截图20190616222150](https://user-images.githubusercontent.com/51079858/59565360-3245dc00-9085-11e9-9837-f479385694c8.png)

**Comment by zhongjianhua163** [comment]
上面截图中的这些测试，我把释放内存的代码屏蔽，但也出现了复用，所以并没有内存泄露的问题。
之前是考虑和测试不够谨慎。。

**Comment by MikuPy2001** [comment]
喵使用了最先进的修复大法:"这个释放代码,喵当初忘了加"

**Comment by zhongjianhua163** [comment]
牛B。
