### ISSUE TITLE
应用加载失败 错误:AppInfo返回消息解析错误(-107)

### ISSUE THREAD

**Issue by ConstStar** [MikuPy2001/CQSDK#15]
在酷Q中点击启用后提醒 应用加载失败 错误:AppInfo返回消息解析错误(-107)

appinfo.h文件内容:
‘’‘
#define APP_ID "cn.xiaoxiaoge.test"
// 应用名称
#define APP_name "test"

// 应用版本
#include "appVer.h"

// 应用作者
#define APP_author "test"

//一句话描述插件用途
#define APP_description "test" //按时发顺丰
#define 填写示例 "示例""""\n第二行,"
//              ↑    ↑           ↑
//              ↑始终第一个引号开始,无论是否是真实引号
//                    ↑中间引号全部忽略,与VS解释有所不同
//                                 ↑直接匹配最后一个引号作为结束

//权限确认,请只保留关键权限.
//#define APP_auth_20 "取Cookies"//[敏感]
//#define APP_auth_30 "接收语音"
#define APP_auth_101 "发送群消息"
#define APP_auth_103 "发送讨论组消息"
#define APP_auth_106 "发送私聊消息"
//#define APP_auth_110 "发送赞"//[敏感]
#define APP_auth_120 "置群员移除"
#define APP_auth_121 "置群员禁言"
#define APP_auth_122 "置群管理员"
#define APP_auth_123 "置全群禁言"
#define APP_auth_124 "置匿名群员禁言"
#define APP_auth_125 "置群匿名设置"
#define APP_auth_126 "置群成员名片"
//#define APP_auth_127 "置群退出"//[敏感]
#define APP_auth_128 "置群成员专属头衔"
#define APP_auth_130 "取群成员信息"
#define APP_auth_131 "取陌生人信息"
#define APP_auth_140 "置讨论组退出"
#define APP_auth_150 "置好友添加请求"
#define APP_auth_151 "置群添加请求"
#define APP_auth_160 "取群成员列表"
#define APP_auth_161 "取群列表"
#define APP_auth_180 "撤回消息"

//酷Q目录,直接生成到酷Q目录
#define CQ_DIR "D:\\用户文档\\桌面\\桌面整理\\酷Q\\"

//接下来请转到 appmain.cpp 以继续
           
‘’’

appVer.h文件内容:
'''
#pragma once

// 应用版本
#define APP_version "1.0.1"

// 应用顺序版本（每次发布时小工具自动将其+1）
// 必须为纯数字,否则将会解析失败
#define APP_version_id 1
  
'''

**Comment by MikuPy2001** [comment]
已经解决,请查看最新的推送,你只需要进行简单的修改即可运行
