### ISSUE TITLE
找不到CQ_SDK.lib

### ISSUE THREAD

**Issue by ConstStar** [MikuPy2001/CQSDK#17]
LNK1104	无法打开文件“CQ_SDK.lib”	CQ_APP

**Comment by MikuPy2001** [comment]
喵喵喵

**Comment by ConstStar** [comment]
新加的几个函数:
	//取好友列表 Auth=
	CQAPI(CQ_getFriendList, 文本型)(
		整数型 AuthCode,
		逻辑型 reserved
		);

	//取群信息(支持缓存) Auth=
	CQAPI(CQ_getGroupInfo, 文本型)(
		整数型 AuthCode,
		长整数型 群号,//目标群
		逻辑型 不使用缓存
		);

	//取Cookies Auth=20 
	//慎用,此接口需要严格授权
	CQAPI(CQ_getCookies, 文本型)(
		整数型 AuthCode,
		文本型 domain//目标域名，如 api.example.com
		);

提醒错误:
“CQ_getCookies”: 无法使用 "C" 链接	CQ_APP

**Comment by MikuPy2001** [comment]
这部分还没完善

**Comment by ConstStar** [comment]
ok，谢谢

**Comment by MikuPy2001** [comment]
啊,完善了,请用1.1版本
