### ISSUE TITLE
缺少lib

### ISSUE THREAD

**Issue by ConstStar** [MikuPy2001/CQSDK#18]
没有lib
debug模式: 无法打开文件“CQ_SDK_DEBUG.lib”
release模式: 无法打开文件“CQ_SDK.lib"

**Comment by MikuPy2001** [comment]
不!喵不信!!

**Comment by ConstStar** [comment]
文件夹里只有CQP.lib 没找到CQ_SDK.lib，我记得在第一个版本里有这个两个文件
还有插件描述（APP_description）如何使用回行，使用\r\n会被转义成\\r\\n

**Comment by MikuPy2001** [comment]
喵了一眼,1.1版本没附上CQAPP.zip,上传失败了

**Comment by MikuPy2001** [comment]
至于换行,喵看了一眼,压根没写转义2333

**Comment by ConstStar** [comment]
好吧，我去试试，谢谢了

**Comment by MikuPy2001** [comment]
你不是有喵的QQ么

**Comment by ConstStar** [comment]
刚加，你还没同意。。。

**Comment by MikuPy2001** [comment]
应该没问题了吧,然后喵就把它关掉了
