### ISSUE TITLE
“crtdbg.h”: No such file or directory

### ISSUE THREAD

**Issue by sosyz** [MikuPy2001/CQSDK#19]
系统 :Win10
环境: vs2019 vc++ 2015已安装
clone后打开进行生成输出以下错误

1>------ 已启动生成: 项目: CQ_APP, 配置: Debug Win32 ------
1>appinfo.h
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\yvals.h(12,10): fatal error C1083: 无法打开包括文件: “crtdbg.h”: No such file or directory
1>appmain.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\yvals.h(12,10): fatal error C1083: 无法打开包括文件: “crtdbg.h”: No such file or directory
1>DEBUG.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\yvals.h(12,10): fatal error C1083: 无法打开包括文件: “crtdbg.h”: No such file or directory
1>dllmain.cpp
1>C:\Users\81414\Documents\code\C++\SeekMsg\CQ_APP\dllmain.cpp(3,10): fatal error C1083: 无法打开包括文件: “Windows.h”: No such file or directory
1>Msg.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\yvals.h(12,10): fatal error C1083: 无法打开包括文件: “crtdbg.h”: No such file or directory
1>源.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\yvals.h(12,10): fatal error C1083: 无法打开包括文件: “crtdbg.h”: No such file or directory
1>正在生成代码...
1>已完成生成项目“CQ_APP.vcxproj”的操作 - 失败。

**Comment by MikuPy2001** [comment]
> 1>C:\Users\81414\Documents\code\C++\SeekMsg\CQ_APP\dllmain.cpp(3,10): fatal error C1083: 无法打开包括文件: “Windows.h”: No such file or directory

> atal error C1083: 无法打开包括文件: “Windows.h”: No such file or directory

> **无法打开包括文件: “Windows.h”**

推测是缺少必要的库文件
[SDK编译条件表](https://github.com/MikuPy2001/CQSDK#%E7%8E%AF%E5%A2%83%E8%A6%81%E6%B1%82)

方案一
首先看有没有安装windows sdk，如果没有安装，
请打开visual Stdio Installer，然后选择修改，勾上最新版的windows SDK
[解决方案来源](https://blog.csdn.net/qq_24264221/article/details/84847417)

**Comment by MikuPy2001** [comment]
有安装平台工具集吗

**Comment by sosyz** [comment]
> 推测是缺少必要的库文件
> [SDK编译条件表](https://github.com/MikuPy2001/CQSDK#%E7%8E%AF%E5%A2%83%E8%A6%81%E6%B1%82)
> 
> 方案一
> 首先看有没有安装windows sdk，如果没有安装，
> 请打开visual Stdio Installer，然后选择修改，勾上最新版的windows SDK
> [解决方案来源](https://blog.csdn.net/qq_24264221/article/details/84847417)

感谢！参照方案一已经解决，不知道是不是我操作问题之前在单个组件安装的Windows 10 10.0.18362没用。
