### ISSUE TITLE
CQ码错误

### ISSUE THREAD

**Issue by sosyz** [MikuPy2001/CQSDK#20]
使用`code::at(111111)`
发送出去的是
[CQ:at,Account=111111]

**Comment by MikuPy2001** [comment]
已经在 015f1ad 修复了

**Comment by sosyz** [comment]
> 已经在 [015f1ad](https://github.com/MikuPy2001/CQSDK/commit/015f1ade27f2c745653071b482a089fde656c106) 修复了

👌翻了下原来是按照文档下载的包没有更新这个文件，才出现了这个问题
