### ISSUE TITLE
API.cpp里有个BUG

### ISSUE THREAD

**Issue by zhongjianhua163** [MikuPy2001/CQSDK#9]
取群成员列表的函数( CQ::getGroupMemberList(长整数型 群号) )里有这么一个 循环：
	auto i = u.getInt();
	while (--i && u.len() > 0)
	{
		//infovector.push_back(GroupMemberInfo(u.getchars()));
		infovector.emplace_back(u.getUnpack());
	}
如果群里只有1个成员的时候，这个i==1，那么  --i 是先减 然后才判断，此时i为0，条件不成立，不进入循环。那么群只有一个成员的时候，是取不出来的。
即使群里不止一个人，，那么取出来的结果也会少一个人。

**Comment by MikuPy2001** [comment]
已修复
